FROM python:3.6

LABEL maintainer="kay.wuensche@gmx.de"

COPY docker/requirements.txt .
RUN pip install -r requirements.txt

COPY src/main /main
WORKDIR /main

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5002"]
